general:
  model_name_or_path: "facebook/opt-1.3b" # "/data1/mingjia/Llama-2-13b-hf" # 
  model_simcse: "princeton-nlp/sup-simcse-roberta-base"
  load_fp16: true
  use_gpu: true

dataset:
  dataset_name: "c4"
  dataset_config_name: "realnewslike"
  dataset_split: "validation"
  split: "test"
  stream_dataset: true
  columns_to_remove: ""
  shuffle_dataset: false
  shuffle_seed: 1234
  shuffle_buffer_size: 10000

generation:
  max_new_tokens: 200
  min_prompt_tokens: 300
  max_input_len: 1000
  limit_indices: null
  input_truncation_strategy: "completion_length"
  input_filtering_strategy: "prompt_and_completion_length"
  output_filtering_strategy: "max_new_tokens"
  use_sampling: true
  sampling_temp: 1.0
  top_k: 50
  generation_seed: null
  batch_size: 20

watermark:
  scheme: "KGW" 
  ignore_repeated_bigrams: false
  detection_z_threshold: 4.0
  ckpt_path: ""
  normalizers: ""
  gamma: 0.25
  delta: 2.0
  seeding_scheme: "simple_1"
  store_spike_ents: true

logging:
  output_dir: "eval"
  log_generated_text: True

